[package]
name = "close-account-api"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck.workspace = true
jzon = "0.12.5"
num_enum.workspace = true
solana-program.workspace = true
steel.workspace = true
thiserror.workspace = true
